export const pizzaData = [
  {
    id: 1,
    name: "Terminal Pizza",
    rating: 4.9,
    comments: 200,
    price: 60,
    imgUrl: "../../../Assets/mile2-aseets/pictures/food-1.png",
    category: "Pizza",
  },
  {
    id: 2,
    name: "Position Absolute Acı Pizza",
    rating: 4.6,
    comments: 928,
    price: 85,
    imgUrl: "../../../Assets/mile2-aseets/pictures/food-2.png",
    category: "Pizza",
  },
  {
    id: 3,
    name: "useEffect Tavuklu Burger",
    rating: 4.2,
    comments: 462,
    price: 75,
    imgUrl: "../../../Assets/mile2-aseets/pictures/food-3.png",
    category: "Burger",
  },
  {
    id: 4,
    name: "Shoyu ramen",
    rating: 4.8,
    comments: 56,
    price: 375,
    imgUrl: "../../../Assets/mile2-aseets/pictures/shoyu-ramen.webp",
    category: "Ramen",
  },
  {
    id: 5,
    name: "Miso ramen",
    rating: 4.3,
    comments: 114,
    price: 298,
    imgUrl: "../../../Assets/mile2-aseets/pictures/miso-ramen.png",
    category: "Ramen",
  },
  {
    id: 6,
    name: "Smash Burger",
    rating: 3.8,
    comments: 424,
    price: 188,
    imgUrl: "../../../Assets/mile2-aseets/pictures/smash-burger.png",
    category: "Burger",
  },
  {
    id: 7,
    name: "Regular Fries",
    rating: 4.8,
    comments: 1641,
    price: 49,
    imgUrl: "../../../Assets/mile2-aseets/pictures/fries.png",
    category: "French Fries",
  },
  {
    id: 8,
    name: "Cheddar Fries",
    rating: 4.2,
    comments: 786,
    price: 64,
    imgUrl: "../../../Assets/mile2-aseets/pictures/fries-cheddar.png",
    category: "French Fries",
  },
  {
    id: 9,
    name: "Taco",
    rating: 4.9,
    comments: 415,
    price: 215,
    imgUrl: "../../../Assets/mile2-aseets/pictures/taco.png",
    category: "Fast Food",
  },
  {
    id: 10,
    name: "Nachos",
    rating: 4.6,
    comments: 86,
    price: 142,
    imgUrl: "../../../Assets/mile2-aseets/pictures/nachos.png",
    category: "Fast Food",
  },
  {
    id: 11,
    name: "Coke",
    rating: 3.1,
    comments: 15,
    price: 9,
    imgUrl: "../../../Assets/mile2-aseets/pictures/coke.png",
    category: "Soft Drinks",
  },
  {
    id: 12,
    name: "Sprite",
    rating: 3.3,
    comments: 26,
    price: 9,
    imgUrl: "../../../Assets/mile2-aseets/pictures/sprite.png",
    category: "Soft Drinks",
  },
];

export const barElements = [
  {
    id: 1,
    title: "Ramen",
    imgSrc: "../../../Assets/mile2-aseets/icons/1.svg",
  },
  {
    id: 2,
    title: "Pizza",
    imgSrc: "../../../Assets/mile2-aseets/icons/2.svg",
  },
  {
    id: 3,
    title: "Burger",
    imgSrc: "../../../Assets/mile2-aseets/icons/3.svg",
  },
  {
    id: 4,
    title: "French Fries",
    imgSrc: "../../../Assets/mile2-aseets/icons/4.svg",
  },
  {
    id: 5,
    title: "Fast Food",
    imgSrc: "../../../Assets/mile2-aseets/icons/5.svg",
  },
  {
    id: 6,
    title: "Soft Drinks",
    imgSrc: "../../../Assets/mile2-aseets/icons/6.svg",
  },
];

export const products = [
  {
    id: 1,
    title: "YENİ! Kore",
    imgSrc: "../../../Assets/mile2-aseets/icons/1.svg",
  },
  {
    id: 2,
    title: "Pizza",
    imgSrc: "../../../Assets/mile2-aseets/icons/2.svg",
  },
  {
    id: 3,
    title: "Burger",
    imgSrc: "../../../Assets/mile2-aseets/icons/3.svg",
  },
  {
    id: 4,
    title: "Kızartmalar",
    imgSrc: "../../../Assets/mile2-aseets/icons/4.svg",
  },
  {
    id: 5,
    title: "Fast Food",
    imgSrc: "../../../Assets/mile2-aseets/icons/5.svg",
  },
  {
    id: 6,
    title: "Gazlı İçecek",
    imgSrc: "../../../Assets/mile2-aseets/icons/6.svg",
  },
];
